name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-

        - name: Set up environment variables
          run: |
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
            
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Django unit tests
          run: |
            python manage.py test

        - name: Merge to Main on Success
          if: success()
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git checkout main
            git merge --ff-only ${{ github.sha }}
            git push origin main
