name: Testing

on:
  push:
    branches:
      # - develop
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  download_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: |
            echo "SECRET_KEY=${SECRET_KEY}"


      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload dependencies as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: venv
          if-no-files-found: error
  
  tests:
    needs: [download_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Download dependencies artifact
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: venv
          if-no-files-found: error
          
      - name: Activate virtual environment
        run: . venv/bin/activate

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Run Django unit tests
        run: |
          cp -r ~/dependencies/. ~/.
          python manage.py test
          

  pull_request_to_main_branch:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request to main on success
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          commit-message: "Merge develop into main"
          title: "Merge develop into main"
          body: "This is an automated pull request to merge develop into main."
          branch: main
          base: develop
