
name: Testing

on:
  push:
    branches:
      - develop


      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

  
jobs:

  dependencies_and_test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-pip-

      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django unit tests
        run: |
          python manage.py test
          
  merge_into_main_branch:
    runs-on: ubuntu-latest
    needs: [dependencies_and_test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'












      # - name: Create Pull Request to main on success
      #   if: github.event_name == 'push'
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{  secrets.TOKEN_GITHUB  }}
      #     commit-message: "Merge develop into main"
      #     title: "Merge develop into main"
      #     body: "This is an automated pull request to merge develop into main."
      #     branch: main
      #     base: develop
