name: Update server

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


    
jobs:

  updating_server:
    runs-on: self-hosted
    steps:
    - name: Print Hola
      run: echo "hola"