name: Update server

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


    
jobs:

  updating_server:
    runs-on: self-hosted
    steps:
    - name: console steps
      run: |
        cd /home/power-gym.com.ar/public_html/capstone
        sudo bash ./build.sh
        